# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      gradle-general-patch-dependencies:
        update-types:
          - "patch"
        patterns:
          - "*"
      kotlin-compose-dependencies:
        update-types:
          - "minor"
          - "major"
        patterns:
          - "org.jetbrains.kotlin*"
          - "*compose*"
          - "com.google.accompanist*"
          - "io.kotest*"
      androidx-dependencies:
        update-types:
          - "minor"
          - "major"
        patterns:
          - "androidx*"
        exclude-patterns:
          - "androidx.compose:compose-bom"
          - "androidx.lifecycle:lifecycle-viewmodel-compose"
          - "androidx.test*"
      test-dependencies:
        update-types:
          - "minor"
          - "major"
        patterns:
          - "*junit*"
          - "*robolectric*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      github-actions-patch-dependencies:
        update-types:
          - "patch"
        patterns:
          - "*"
      github-actions-minor-dependencies:
        update-types:
          - "minor"
        patterns:
          - "*"
      github-actions-major-dependencies:
        update-types:
          - "major"
        patterns:
          - "*"
