name: Run pull request CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Run test
        if: always()
        run: ./gradlew testDebugUnitTest --no-daemon